language: cpp
compiler:
  - clang

before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:smspillaz/cmake-master
  - sudo add-apt-repository -y ppa:chris-lea/protobuf
  - sudo add-apt-repository -y ppa:b-s-a/ppa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-beta-proper
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get -y purge cmake
  - sudo apt-get -y install -qq cmake
  - sudo apt-get install -qq g++-4.8 gcc-4.8
  - sudo apt-get install -qq wget liblua5.1-dev libluajit-5.1-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 99 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - sudo apt-get -y install -qq libsqlite3-dev libsoci-sqlite3.2  libsoci3.2-dev
  - sudo apt-get -y install -qq libprotobuf-dev protobuf-compiler
  - sudo apt-get -y install -qq libgloox-dev
  - sudo apt-get -y install -qq libmozjs185-dev
  - sudo apt-get -y install -qq libqt5opengl5-dev libqt5dbus5 qtbase5-dev  libqt5widgets5 qt5-default
  - mkdir -pv build
  - wget http://jaist.dl.sourceforge.net/boost/boost_1_57_0.tar.bz2
  - tar -xf boost_1_57_0.tar.bz2
  - git submodule update --init
  - ( cd boost_1_57_0 && ./bootstrap.sh && sudo ./b2 install --prefix=/usr link=static --with-date_time --with-filesystem --with-exception --with-locale --with-random --with-regex --with-program_options --with-system --with-thread --with-context --with-coroutine --with-timer --with-atomic --with-chrono ) > /dev/null

before_script:
  cd build && LDFLAGS="-lrt" cmake -DENABLE_LUA=on -DENABLE_PYTHON=OFF -DINTERNALGLOOX=OFF ..

script:
  make -j3

notifications:
  recipients:
    - microcaicai@gmail.com
  email:
    on_success: change
    on_failure: change
